import { useState } from "react";
import { BookOpen, Code2, PanelRightOpen, CheckSquare } from "lucide-react";

type ToggleSettingProps = {
    title: string;
    description: string;
    icon: React.ReactNode;
    enabled: boolean;
    onToggle: () => void;
};

function ToggleSetting({ title, description, icon, enabled, onToggle }: ToggleSettingProps) {
    return (
        <div className="flex items-center justify-between p-5 bg-white border border-slate-200 rounded-2xl shadow-sm hover:border-slate-300 transition-all cursor-pointer" onClick={onToggle}>
            <div className="flex items-center gap-4">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 transition-colors ${enabled ? 'bg-blue-50 text-blue-600' : 'bg-slate-100 text-slate-500'}`}>
                    {icon}
                </div>
                <div>
                    <h3 className="font-bold text-slate-900 text-sm">{title}</h3>
                    <p className="text-xs text-slate-500 font-medium mt-0.5">{description}</p>
                </div>
            </div>
            <div className="shrink-0">
                <button
                    className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 ${enabled ? 'bg-blue-600' : 'bg-slate-200'}`}
                    role="switch"
                    aria-checked={enabled}
                >
                    <span
                        className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${enabled ? 'translate-x-6' : 'translate-x-1'}`}
                    />
                </button>
            </div>
        </div>
    );
}

export default function Settings() {
    const [settings, setSettings] = useState({
        showAiQuizzes: true,
        showGenerateAiCode: true,
        showAiPanelByDefault: false,
        acceptCodeChangesByDefault: false,
    });

    const toggleSetting = (key: keyof typeof settings) => {
        setSettings(prev => ({ ...prev, [key]: !prev[key] }));
    };

    return (
        <div className="p-8 max-w-4xl mx-auto flex flex-col gap-8">


            {/* Toggles Section */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <ToggleSetting
                    title="Show AI Quizzes"
                    description="Enable or disable quizzes generated by AI after completing a problem."
                    icon={<BookOpen className="w-5 h-5" />}
                    enabled={settings.showAiQuizzes}
                    onToggle={() => toggleSetting('showAiQuizzes')}
                />
                <ToggleSetting
                    title="Show Generate AI Code"
                    description="Allow AI to write and suggest full code snippets within the editor."
                    icon={<Code2 className="w-5 h-5" />}
                    enabled={settings.showGenerateAiCode}
                    onToggle={() => toggleSetting('showGenerateAiCode')}
                />
                <ToggleSetting
                    title="Show AI Panel By Default"
                    description="Automatically open the right-side AI Co-Pilot panel when entering a workspace."
                    icon={<PanelRightOpen className="w-5 h-5" />}
                    enabled={settings.showAiPanelByDefault}
                    onToggle={() => toggleSetting('showAiPanelByDefault')}
                />
                <ToggleSetting
                    title="Accept Code Changes By Default"
                    description="Automatically apply AI-generated code edits without asking for confirmation."
                    icon={<CheckSquare className="w-5 h-5" />}
                    enabled={settings.acceptCodeChangesByDefault}
                    onToggle={() => toggleSetting('acceptCodeChangesByDefault')}
                />
            </div>
        </div>
    );
}
